version: '3.8'

services:
    app:
        build:
            context: .
            target: production
        container_name: todo-app
        ports:
            - 3000:3000
        working_dir: /app
        env_file:
            - ./.env
        environment:
            MYSQL_HOST: $MYSQL_HOST
            MYSQL_USER_NODE: $MYSQL_USER_NODE
            MYSQL_PASSWORD: $MYSQL_PASSWORD
            MYSQL_DB: $MYSQL_DATABASE
        depends_on:
            - 'mysql'

    mysql:
        image: mysql:5.7
        container_name: mysql-db
        volumes:
            - todo-mysql-data:/var/lib/mysql
        env_file:
            - ./.env
        environment:
            MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
            MYSQL_DATABASE: $MYSQL_DATABASE

volumes:
    todo-mysql-data:
